[project]
name = "agentic-api"
version = "0.1.0"
description = "A modular, cloud-native API for AI Agents powered by FastAPI, Pydantic, and Pydantic AI"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pydantic>=2.13",
    "pydantic-settings>=2.14",
    "pydantic-ai>=2.27",
    "httpx>=0.28",
    "fastapi>=0.141",
    "uvicorn>=0.52",
]

[project.scripts]
agentic = "agentic.main:start_web_server"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ruff>=0.16",
    "ty>=0.0.69",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.0",
]

codegen = [
    "ariadne-codegen>=0.18"
]

[tool.uv]
conflicts = [
    [{"group" = "dev"}, {"group" = "codegen"}]
]

[tool.ruff.lint]
ignore = ["B008"]

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "auto"

[tool.hatch.build.targets.wheel]
packages = ["src/agentic"]

[tool.ariadne-codegen]
# [REMOTE] Endpoint & Authentication Configuration
# remote_schema_url = "$FIBERY_GRAPHQL_URL"
# remote_schema_headers = { "Authorization" = "Token $FIBERY_GRAPHQL_AUTH_TOKEN" }

# [REMOTE] Optional SSL and timeout configurations
# remote_schema_verify_ssl = true
# remote_schema_timeout = 10

# [LOCAL] Output location when downloading the schema
target_file_path = "src/agentic/ai/tools/fibery/graphql_client/schema.graphql"

# [LOCAL] Client Query Generation
queries_path = "src/agentic/ai/tools/fibery/graphql_client/queries.graphql"
target_package_name = "graphql_client"
target_package_path = "src/agentic/ai/tools/fibery"

# [LOCAL] Client Schema Generation
schema_path = "src/agentic/ai/tools/fibery/graphql_client/schema.graphql"