# Generated by ariadne-codegen
# Source: src/agentic/ai/tools/fibery/graphql_client/queries.graphql

from typing import Any

from .async_base_client import AsyncBaseClient
from .get_emails import GetEmails
from .update_email_rubric import UpdateEmailRubric


def gql(q: str) -> str:
    return q


class Client(AsyncBaseClient):
    async def get_emails(self, **kwargs: Any) -> GetEmails:
        query = gql("""
            query GetEmails {
              findEmails(limit: 100) {
                publicId
                name
                date
                email
                message {
                  md
                }
                from {
                  name
                  email
                }
                files {
                  name
                  url
                }
                rubric
              }
            }
            """)
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query, operation_name="GetEmails", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetEmails.model_validate(data)

    async def update_email_rubric(
        self, public_id: str, rubric: int, **kwargs: Any
    ) -> UpdateEmailRubric:
        query = gql("""
            mutation UpdateEmailRubric($publicId: String!, $rubric: Int!) {
              emails(publicId: {is: $publicId}) {
                update(rubric: $rubric) {
                  message
                }
              }
            }
            """)
        variables: dict[str, object] = {"publicId": public_id, "rubric": rubric}
        response = await self.execute(
            query=query,
            operation_name="UpdateEmailRubric",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return UpdateEmailRubric.model_validate(data)
