# Generated by ariadne-codegen
# Source: src/agentic/ai/tools/fibery/graphql_client/schema.graphql

from enum import Enum


class Order(str, Enum):
    ASC = "ASC"
    DESC = "DESC"


class JobStatus(str, Enum):
    EXECUTING = "EXECUTING"
    FAILED = "FAILED"
    COMPLETED = "COMPLETED"
