# Generated by ariadne-codegen
# Source: src/agentic/ai/tools/fibery/graphql_client/queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class GetEmails(BaseModel):
    find_emails: Optional[list[Optional["GetEmailsFindEmails"]]] = Field(
        alias="findEmails"
    )


class GetEmailsFindEmails(BaseModel):
    public_id: Optional[str] = Field(alias="publicId")
    name: Optional[str]
    date: Optional[str]
    email: Optional[str]
    message: Optional["GetEmailsFindEmailsMessage"]
    from_: Optional["GetEmailsFindEmailsFrom"] = Field(alias="from")
    files: Optional[list[Optional["GetEmailsFindEmailsFiles"]]]
    rubric: Optional[int]


class GetEmailsFindEmailsMessage(BaseModel):
    md: Optional[str]


class GetEmailsFindEmailsFrom(BaseModel):
    name: Optional[str]
    email: Optional[str]


class GetEmailsFindEmailsFiles(BaseModel):
    name: Optional[str]
    url: Optional[str]


GetEmails.model_rebuild()
GetEmailsFindEmails.model_rebuild()
