# Generated by ariadne-codegen
# Source: src/agentic/ai/tools/fibery/graphql_client/schema.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import Order


class EmailEmailInput(BaseModel):
    rank: Optional[float] = None
    rubric: Optional[int] = None


class EmailEmailOrder(BaseModel):
    id: Optional[Order] = None
    sync_id: Optional[Order] = Field(alias="syncId", default=None)
    public_id: Optional[Order] = Field(alias="publicId", default=None)
    creation_date: Optional[Order] = Field(alias="creationDate", default=None)
    modification_date: Optional[Order] = Field(alias="modificationDate", default=None)
    rank: Optional[Order] = None
    created_by: Optional["FiberyUserOrder"] = Field(alias="createdBy", default=None)
    cc_1: Optional[Order] = Field(alias="cc1", default=None)
    date: Optional[Order] = None
    deleted_in_email: Optional[Order] = Field(alias="deletedInEmail", default=None)
    delivered_to: Optional[Order] = Field(alias="deliveredTo", default=None)
    email: Optional[Order] = None
    email_url: Optional[Order] = Field(alias="emailUrl", default=None)
    folder: Optional[Order] = None
    from_: Optional["EmailEmailContactOrder"] = Field(alias="from", default=None)
    from_1: Optional[Order] = Field(alias="from1", default=None)
    name: Optional[Order] = None
    original_message_id: Optional[Order] = Field(
        alias="originalMessageId", default=None
    )
    reply_to_text: Optional[Order] = Field(alias="replyToText", default=None)
    thread: Optional["EmailEmailOrder"] = None
    thread_1: Optional[Order] = Field(alias="thread1", default=None)
    to_1: Optional[Order] = Field(alias="to1", default=None)
    rubric: Optional[Order] = None


class EmailEmailFilter(BaseModel):
    order_by: Optional["EmailEmailOrder"] = Field(alias="orderBy", default=None)
    limit: Optional[int] = None
    offset: Optional[int] = None
    id: Optional["IDFilter"] = None
    sync_id: Optional["StringFilter"] = Field(alias="syncId", default=None)
    public_id: Optional["StringFilter"] = Field(alias="publicId", default=None)
    creation_date: Optional["StringFilter"] = Field(alias="creationDate", default=None)
    modification_date: Optional["StringFilter"] = Field(
        alias="modificationDate", default=None
    )
    rank: Optional["FloatFilter"] = None
    created_by: Optional["FiberyUserFilter"] = Field(alias="createdBy", default=None)
    cc: Optional["EmailEmailContactCollectionFilter"] = None
    cc_1: Optional["StringFilter"] = Field(alias="cc1", default=None)
    date: Optional["StringFilter"] = None
    deleted_in_email: Optional["StringFilter"] = Field(
        alias="deletedInEmail", default=None
    )
    delivered_to: Optional["StringFilter"] = Field(alias="deliveredTo", default=None)
    email: Optional["StringFilter"] = None
    email_url: Optional["StringFilter"] = Field(alias="emailUrl", default=None)
    files: Optional["FiberyFileCollectionFilter"] = None
    folder: Optional["StringFilter"] = None
    from_: Optional["EmailEmailContactFilter"] = Field(alias="from", default=None)
    from_1: Optional["StringFilter"] = Field(alias="from1", default=None)
    name: Optional["StringFilter"] = None
    original_message_id: Optional["StringFilter"] = Field(
        alias="originalMessageId", default=None
    )
    replies: Optional["EmailEmailCollectionFilter"] = None
    reply_to_text: Optional["StringFilter"] = Field(alias="replyToText", default=None)
    thread: Optional["EmailEmailFilter"] = None
    thread_1: Optional["StringFilter"] = Field(alias="thread1", default=None)
    to: Optional["EmailEmailContactCollectionFilter"] = None
    to_1: Optional["StringFilter"] = Field(alias="to1", default=None)
    rubric: Optional["IntFilter"] = None


class EmailEmailCollectionFilter(BaseModel):
    is_empty: Optional[bool] = Field(alias="isEmpty", default=None)
    contains: Optional[list[Optional["EmailEmailFilter"]]] = None
    contains_any: Optional[list[Optional["EmailEmailFilter"]]] = Field(
        alias="containsAny", default=None
    )
    not_contains: Optional[list[Optional["EmailEmailFilter"]]] = Field(
        alias="notContains", default=None
    )
    not_contains_any: Optional[list[Optional["EmailEmailFilter"]]] = Field(
        alias="notContainsAny", default=None
    )


class EmailEmailContactInput(BaseModel):
    rank: Optional[float] = None


class EmailEmailContactOrder(BaseModel):
    id: Optional[Order] = None
    sync_id: Optional[Order] = Field(alias="syncId", default=None)
    public_id: Optional[Order] = Field(alias="publicId", default=None)
    creation_date: Optional[Order] = Field(alias="creationDate", default=None)
    modification_date: Optional[Order] = Field(alias="modificationDate", default=None)
    rank: Optional[Order] = None
    created_by: Optional["FiberyUserOrder"] = Field(alias="createdBy", default=None)
    deleted_in_email: Optional[Order] = Field(alias="deletedInEmail", default=None)
    email: Optional[Order] = None
    name: Optional[Order] = None


class EmailEmailContactFilter(BaseModel):
    order_by: Optional["EmailEmailContactOrder"] = Field(alias="orderBy", default=None)
    limit: Optional[int] = None
    offset: Optional[int] = None
    id: Optional["IDFilter"] = None
    sync_id: Optional["StringFilter"] = Field(alias="syncId", default=None)
    public_id: Optional["StringFilter"] = Field(alias="publicId", default=None)
    creation_date: Optional["StringFilter"] = Field(alias="creationDate", default=None)
    modification_date: Optional["StringFilter"] = Field(
        alias="modificationDate", default=None
    )
    rank: Optional["FloatFilter"] = None
    created_by: Optional["FiberyUserFilter"] = Field(alias="createdBy", default=None)
    deleted_in_email: Optional["StringFilter"] = Field(
        alias="deletedInEmail", default=None
    )
    email: Optional["StringFilter"] = None
    emails_cc: Optional["EmailEmailCollectionFilter"] = Field(
        alias="emailsCc", default=None
    )
    emails_from: Optional["EmailEmailCollectionFilter"] = Field(
        alias="emailsFrom", default=None
    )
    emails_to: Optional["EmailEmailCollectionFilter"] = Field(
        alias="emailsTo", default=None
    )
    name: Optional["StringFilter"] = None


class EmailEmailContactCollectionFilter(BaseModel):
    is_empty: Optional[bool] = Field(alias="isEmpty", default=None)
    contains: Optional[list[Optional["EmailEmailContactFilter"]]] = None
    contains_any: Optional[list[Optional["EmailEmailContactFilter"]]] = Field(
        alias="containsAny", default=None
    )
    not_contains: Optional[list[Optional["EmailEmailContactFilter"]]] = Field(
        alias="notContains", default=None
    )
    not_contains_any: Optional[list[Optional["EmailEmailContactFilter"]]] = Field(
        alias="notContainsAny", default=None
    )


class FiberyUserInput(BaseModel):
    role: Optional[str] = None
    rank: Optional[float] = None
    name: Optional[str] = None


class FiberyUserOrder(BaseModel):
    active: Optional[Order] = None
    id: Optional[Order] = None
    role: Optional[Order] = None
    public_id: Optional[Order] = Field(alias="publicId", default=None)
    creation_date: Optional[Order] = Field(alias="creationDate", default=None)
    modification_date: Optional[Order] = Field(alias="modificationDate", default=None)
    rank: Optional[Order] = None
    email: Optional[Order] = None
    name: Optional[Order] = None


class FiberyUserFilter(BaseModel):
    order_by: Optional["FiberyUserOrder"] = Field(alias="orderBy", default=None)
    limit: Optional[int] = None
    offset: Optional[int] = None
    active: Optional["BooleanFilter"] = None
    id: Optional["IDFilter"] = None
    role: Optional["StringFilter"] = None
    public_id: Optional["StringFilter"] = Field(alias="publicId", default=None)
    creation_date: Optional["StringFilter"] = Field(alias="creationDate", default=None)
    modification_date: Optional["StringFilter"] = Field(
        alias="modificationDate", default=None
    )
    rank: Optional["FloatFilter"] = None
    email: Optional["StringFilter"] = None
    name: Optional["StringFilter"] = None


class FiberyUserCollectionFilter(BaseModel):
    is_empty: Optional[bool] = Field(alias="isEmpty", default=None)
    contains: Optional[list[Optional["FiberyUserFilter"]]] = None
    contains_any: Optional[list[Optional["FiberyUserFilter"]]] = Field(
        alias="containsAny", default=None
    )
    not_contains: Optional[list[Optional["FiberyUserFilter"]]] = Field(
        alias="notContains", default=None
    )
    not_contains_any: Optional[list[Optional["FiberyUserFilter"]]] = Field(
        alias="notContainsAny", default=None
    )


class FiberyFileInput(BaseModel):
    name: Optional[str] = None
    rank: Optional[float] = None


class FiberyFileOrder(BaseModel):
    content_length: Optional[Order] = Field(alias="contentLength", default=None)
    content_type: Optional[Order] = Field(alias="contentType", default=None)
    id: Optional[Order] = None
    name: Optional[Order] = None
    secret: Optional[Order] = None
    creation_date: Optional[Order] = Field(alias="creationDate", default=None)
    rank: Optional[Order] = None


class FiberyFileFilter(BaseModel):
    order_by: Optional["FiberyFileOrder"] = Field(alias="orderBy", default=None)
    limit: Optional[int] = None
    offset: Optional[int] = None
    content_length: Optional["FloatFilter"] = Field(alias="contentLength", default=None)
    content_type: Optional["StringFilter"] = Field(alias="contentType", default=None)
    id: Optional["IDFilter"] = None
    name: Optional["StringFilter"] = None
    secret: Optional["StringFilter"] = None
    creation_date: Optional["StringFilter"] = Field(alias="creationDate", default=None)
    rank: Optional["FloatFilter"] = None


class FiberyFileCollectionFilter(BaseModel):
    is_empty: Optional[bool] = Field(alias="isEmpty", default=None)
    contains: Optional[list[Optional["FiberyFileFilter"]]] = None
    contains_any: Optional[list[Optional["FiberyFileFilter"]]] = Field(
        alias="containsAny", default=None
    )
    not_contains: Optional[list[Optional["FiberyFileFilter"]]] = Field(
        alias="notContains", default=None
    )
    not_contains_any: Optional[list[Optional["FiberyFileFilter"]]] = Field(
        alias="notContainsAny", default=None
    )


class StringFilter(BaseModel):
    is_: Optional[str] = Field(alias="is", default=None)
    is_not: Optional[str] = Field(alias="isNot", default=None)
    contains: Optional[str] = None
    not_contains: Optional[str] = Field(alias="notContains", default=None)
    greater: Optional[str] = None
    greater_or_equals: Optional[str] = Field(alias="greaterOrEquals", default=None)
    less: Optional[str] = None
    less_or_equals: Optional[str] = Field(alias="lessOrEquals", default=None)
    in_: Optional[list[Optional[str]]] = Field(alias="in", default=None)
    not_in: Optional[list[Optional[str]]] = Field(alias="notIn", default=None)
    is_null: Optional[bool] = Field(alias="isNull", default=None)


class FloatFilter(BaseModel):
    is_: Optional[float] = Field(alias="is", default=None)
    is_not: Optional[float] = Field(alias="isNot", default=None)
    greater: Optional[float] = None
    greater_or_equals: Optional[float] = Field(alias="greaterOrEquals", default=None)
    less: Optional[float] = None
    less_or_equals: Optional[float] = Field(alias="lessOrEquals", default=None)
    in_: Optional[list[Optional[float]]] = Field(alias="in", default=None)
    not_in: Optional[list[Optional[float]]] = Field(alias="notIn", default=None)
    is_null: Optional[bool] = Field(alias="isNull", default=None)


class IDFilter(BaseModel):
    is_: Optional[str] = Field(alias="is", default=None)
    is_not: Optional[str] = Field(alias="isNot", default=None)
    in_: Optional[list[Optional[str]]] = Field(alias="in", default=None)
    not_in: Optional[list[Optional[str]]] = Field(alias="notIn", default=None)
    is_null: Optional[bool] = Field(alias="isNull", default=None)


class IntFilter(BaseModel):
    is_: Optional[int] = Field(alias="is", default=None)
    is_not: Optional[int] = Field(alias="isNot", default=None)
    greater: Optional[int] = None
    greater_or_equals: Optional[int] = Field(alias="greaterOrEquals", default=None)
    less: Optional[int] = None
    less_or_equals: Optional[int] = Field(alias="lessOrEquals", default=None)
    in_: Optional[list[Optional[int]]] = Field(alias="in", default=None)
    not_in: Optional[list[Optional[int]]] = Field(alias="notIn", default=None)
    is_null: Optional[bool] = Field(alias="isNull", default=None)


class BooleanFilter(BaseModel):
    is_: Optional[bool] = Field(alias="is", default=None)
    is_null: Optional[bool] = Field(alias="isNull", default=None)


class DateRangeFilter(BaseModel):
    start: Optional["StringFilter"] = None
    end: Optional["StringFilter"] = None
    is_null: Optional[bool] = Field(alias="isNull", default=None)


class DateRangeInput(BaseModel):
    start: Optional[str] = None
    end: Optional[str] = None


class AddressPartsInput(BaseModel):
    poi: Optional[str] = None
    postcode: Optional[str] = None
    locality: Optional[str] = None
    place: Optional[str] = None
    district: Optional[str] = None
    neighborhood: Optional[str] = None
    address: Optional[str] = None
    region: Optional[str] = None
    country: Optional[str] = None


class LocationFilter(BaseModel):
    is_null: Optional[bool] = Field(alias="isNull", default=None)


class LocationInput(BaseModel):
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    full_address: Optional[str] = Field(alias="fullAddress", default=None)
    address_parts: Optional["AddressPartsInput"] = Field(
        alias="addressParts", default=None
    )


class DateRangeOrder(BaseModel):
    start: Optional[Order] = None
    end: Optional[Order] = None


class ScriptInput(BaseModel):
    script: Optional[str] = None


class SendWebRequestInput(BaseModel):
    http_request_config: Optional[str] = Field(alias="httpRequestConfig", default=None)


class UpdateCcInput(BaseModel):
    filter_: Optional["EmailEmailContactFilter"] = Field(alias="filter", default=None)
    fields: Optional["EmailEmailContactInput"] = None


class AppendContentToMessageInput(BaseModel):
    value: Optional[str] = None


class PrependContentToMessageInput(BaseModel):
    value: Optional[str] = None


class OverwriteMessageInput(BaseModel):
    value: Optional[str] = None


class UpdateRepliesInput(BaseModel):
    filter_: Optional["EmailEmailFilter"] = Field(alias="filter", default=None)
    fields: Optional["EmailEmailInput"] = None


class UpdateToInput(BaseModel):
    filter_: Optional["EmailEmailContactFilter"] = Field(alias="filter", default=None)
    fields: Optional["EmailEmailContactInput"] = None


class AddFileToFilesFromUrlInput(BaseModel):
    name: Optional[str] = None
    url: Optional[str] = None


class AttachPdfToFilesUsingTemplateInput(BaseModel):
    name: Optional[str] = None
    value: Optional[str] = None
    html_page: Optional[bool] = Field(alias="htmlPage", default=None)


class NotifyCreatedByInput(BaseModel):
    subject: Optional[str] = None
    message: Optional[str] = None
    notify_author: Optional[bool] = Field(alias="notifyAuthor", default=None)


class NotifyUsersInput(BaseModel):
    to: Optional[list[Optional["FiberyUserFilter"]]] = None
    subject: Optional[str] = None
    message: Optional[str] = None
    notify_author: Optional[bool] = Field(alias="notifyAuthor", default=None)
    no_empty_send: Optional[bool] = Field(alias="noEmptySend", default=None)


class UpdateEmailsCcInput(BaseModel):
    filter_: Optional["EmailEmailFilter"] = Field(alias="filter", default=None)
    fields: Optional["EmailEmailInput"] = None


class UpdateEmailsFromInput(BaseModel):
    filter_: Optional["EmailEmailFilter"] = Field(alias="filter", default=None)
    fields: Optional["EmailEmailInput"] = None


class UpdateEmailsToInput(BaseModel):
    filter_: Optional["EmailEmailFilter"] = Field(alias="filter", default=None)
    fields: Optional["EmailEmailInput"] = None


EmailEmailOrder.model_rebuild()
EmailEmailFilter.model_rebuild()
EmailEmailCollectionFilter.model_rebuild()
EmailEmailContactOrder.model_rebuild()
EmailEmailContactFilter.model_rebuild()
EmailEmailContactCollectionFilter.model_rebuild()
FiberyUserFilter.model_rebuild()
FiberyUserCollectionFilter.model_rebuild()
FiberyFileFilter.model_rebuild()
FiberyFileCollectionFilter.model_rebuild()
DateRangeFilter.model_rebuild()
LocationInput.model_rebuild()
UpdateCcInput.model_rebuild()
UpdateRepliesInput.model_rebuild()
UpdateToInput.model_rebuild()
NotifyUsersInput.model_rebuild()
UpdateEmailsCcInput.model_rebuild()
UpdateEmailsFromInput.model_rebuild()
UpdateEmailsToInput.model_rebuild()
