type Query {
  me: FiberyUser
  job(id: String!): BackgroundJob
  findEmails(orderBy: EmailEmailOrder, limit: Int, offset: Int, id: IDFilter, syncId: StringFilter, publicId: StringFilter, creationDate: StringFilter, modificationDate: StringFilter, rank: FloatFilter, createdBy: FiberyUserFilter, cc: EmailEmailContactCollectionFilter, cc1: StringFilter, date: StringFilter, deletedInEmail: StringFilter, deliveredTo: StringFilter, email: StringFilter, emailUrl: StringFilter, files: FiberyFileCollectionFilter, folder: StringFilter, from: EmailEmailContactFilter, from1: StringFilter, name: StringFilter, originalMessageId: StringFilter, replies: EmailEmailCollectionFilter, replyToText: StringFilter, thread: EmailEmailFilter, thread1: StringFilter, to: EmailEmailContactCollectionFilter, to1: StringFilter, rubric: IntFilter): [EmailEmail]
  findEmailContacts(orderBy: EmailEmailContactOrder, limit: Int, offset: Int, id: IDFilter, syncId: StringFilter, publicId: StringFilter, creationDate: StringFilter, modificationDate: StringFilter, rank: FloatFilter, createdBy: FiberyUserFilter, deletedInEmail: StringFilter, email: StringFilter, emailsCc: EmailEmailCollectionFilter, emailsFrom: EmailEmailCollectionFilter, emailsTo: EmailEmailCollectionFilter, name: StringFilter): [EmailEmailContact]
}

type EmailEmail {
  id: ID
  syncId: String
  publicId: String
  creationDate: String
  modificationDate: String
  rank: Float
  createdBy: FiberyUser
  cc(orderBy: EmailEmailContactOrder, limit: Int, id: IDFilter, syncId: StringFilter, publicId: StringFilter, creationDate: StringFilter, modificationDate: StringFilter, rank: FloatFilter, createdBy: FiberyUserFilter, deletedInEmail: StringFilter, email: StringFilter, emailsCc: EmailEmailCollectionFilter, emailsFrom: EmailEmailCollectionFilter, emailsTo: EmailEmailCollectionFilter, name: StringFilter): [EmailEmailContact]
  cc1: String
  date: String
  deletedInEmail: String
  deliveredTo: String
  email: String
  emailUrl: String
  files(orderBy: FiberyFileOrder, limit: Int, contentLength: FloatFilter, contentType: StringFilter, id: IDFilter, name: StringFilter, secret: StringFilter, creationDate: StringFilter, rank: FloatFilter): [FiberyFile]
  folder: String
  from: EmailEmailContact
  from1: String
  message: RichField
  name: String
  originalMessageId: String
  replies(orderBy: EmailEmailOrder, limit: Int, id: IDFilter, syncId: StringFilter, publicId: StringFilter, creationDate: StringFilter, modificationDate: StringFilter, rank: FloatFilter, createdBy: FiberyUserFilter, cc: EmailEmailContactCollectionFilter, cc1: StringFilter, date: StringFilter, deletedInEmail: StringFilter, deliveredTo: StringFilter, email: StringFilter, emailUrl: StringFilter, files: FiberyFileCollectionFilter, folder: StringFilter, from: EmailEmailContactFilter, from1: StringFilter, name: StringFilter, originalMessageId: StringFilter, replies: EmailEmailCollectionFilter, replyToText: StringFilter, thread: EmailEmailFilter, thread1: StringFilter, to: EmailEmailContactCollectionFilter, to1: StringFilter, rubric: IntFilter): [EmailEmail]
  replyToText: String
  thread: EmailEmail
  thread1: String
  to(orderBy: EmailEmailContactOrder, limit: Int, id: IDFilter, syncId: StringFilter, publicId: StringFilter, creationDate: StringFilter, modificationDate: StringFilter, rank: FloatFilter, createdBy: FiberyUserFilter, deletedInEmail: StringFilter, email: StringFilter, emailsCc: EmailEmailCollectionFilter, emailsFrom: EmailEmailCollectionFilter, emailsTo: EmailEmailCollectionFilter, name: StringFilter): [EmailEmailContact]
  to1: String
  rubric: Int
}

input EmailEmailInput {
  rank: Float
  rubric: Int
}

input EmailEmailOrder {
  id: Order
  syncId: Order
  publicId: Order
  creationDate: Order
  modificationDate: Order
  rank: Order
  createdBy: FiberyUserOrder
  cc1: Order
  date: Order
  deletedInEmail: Order
  deliveredTo: Order
  email: Order
  emailUrl: Order
  folder: Order
  from: EmailEmailContactOrder
  from1: Order
  name: Order
  originalMessageId: Order
  replyToText: Order
  thread: EmailEmailOrder
  thread1: Order
  to1: Order
  rubric: Order
}

type EmailEmailBackgroundJob {
  jobId: String
  actions: EmailEmailOperations
}

type EmailEmailOperations {
  executeAsBackgroundJob: EmailEmailBackgroundJob
  create(rank: Float, rubric: Int): MutationResult
  createBatch(data: [EmailEmailInput]): MutationResult
  update(rank: Float, rubric: Int): MutationResult
  updateBatch(data: [EmailEmailInput]): MutationResult
  delete: MutationResult
  script(script: String): MutationResult
  scriptBatch(data: [ScriptInput]): MutationResult
  sendWebRequest(httpRequestConfig: String): MutationResult
  sendWebRequestBatch(data: [SendWebRequestInput]): MutationResult
  updateCc(filter: EmailEmailContactFilter, fields: EmailEmailContactInput): MutationResult
  updateCcBatch(data: [UpdateCcInput]): MutationResult
  updateFrom(rank: Float): MutationResult
  updateFromBatch(data: [EmailEmailContactInput]): MutationResult
  appendContentToMessage(value: String): MutationResult
  appendContentToMessageBatch(data: [AppendContentToMessageInput]): MutationResult
  prependContentToMessage(value: String): MutationResult
  prependContentToMessageBatch(data: [PrependContentToMessageInput]): MutationResult
  overwriteMessage(value: String): MutationResult
  overwriteMessageBatch(data: [OverwriteMessageInput]): MutationResult
  updateReplies(filter: EmailEmailFilter, fields: EmailEmailInput): MutationResult
  updateRepliesBatch(data: [UpdateRepliesInput]): MutationResult
  updateThread(rank: Float, rubric: Int): MutationResult
  updateThreadBatch(data: [EmailEmailInput]): MutationResult
  updateTo(filter: EmailEmailContactFilter, fields: EmailEmailContactInput): MutationResult
  updateToBatch(data: [UpdateToInput]): MutationResult
  addFileToFilesFromUrl(name: String, url: String): MutationResult
  addFileToFilesFromUrlBatch(data: [AddFileToFilesFromUrlInput]): MutationResult
  attachPdfToFilesUsingTemplate(name: String, value: String, htmlPage: Boolean): MutationResult
  attachPdfToFilesUsingTemplateBatch(data: [AttachPdfToFilesUsingTemplateInput]): MutationResult
  deleteFiles(contentLength: FloatFilter, contentType: StringFilter, id: IDFilter, name: StringFilter, secret: StringFilter, creationDate: StringFilter, rank: FloatFilter): MutationResult
  deleteFilesBatch(data: [FiberyFileInput]): MutationResult
  notifyCreatedBy(subject: String, message: String, notifyAuthor: Boolean): MutationResult
  notifyCreatedByBatch(data: [NotifyCreatedByInput]): MutationResult
  notifyUsers(to: [FiberyUserFilter], subject: String, message: String, notifyAuthor: Boolean, noEmptySend: Boolean): MutationResult
  notifyUsersBatch(data: [NotifyUsersInput]): MutationResult
  revokeAccessViaCreatedBy: MutationResult
  countOfEntities: Int
  listEntities: [Entity]
}

input EmailEmailFilter {
  orderBy: EmailEmailOrder
  limit: Int
  offset: Int
  id: IDFilter
  syncId: StringFilter
  publicId: StringFilter
  creationDate: StringFilter
  modificationDate: StringFilter
  rank: FloatFilter
  createdBy: FiberyUserFilter
  cc: EmailEmailContactCollectionFilter
  cc1: StringFilter
  date: StringFilter
  deletedInEmail: StringFilter
  deliveredTo: StringFilter
  email: StringFilter
  emailUrl: StringFilter
  files: FiberyFileCollectionFilter
  folder: StringFilter
  from: EmailEmailContactFilter
  from1: StringFilter
  name: StringFilter
  originalMessageId: StringFilter
  replies: EmailEmailCollectionFilter
  replyToText: StringFilter
  thread: EmailEmailFilter
  thread1: StringFilter
  to: EmailEmailContactCollectionFilter
  to1: StringFilter
  rubric: IntFilter
}

input EmailEmailCollectionFilter {
  isEmpty: Boolean
  contains: [EmailEmailFilter]
  containsAny: [EmailEmailFilter]
  notContains: [EmailEmailFilter]
  notContainsAny: [EmailEmailFilter]
}

type EmailEmailContact {
  id: ID
  syncId: String
  publicId: String
  creationDate: String
  modificationDate: String
  rank: Float
  createdBy: FiberyUser
  deletedInEmail: String
  email: String
  emailsCc(orderBy: EmailEmailOrder, limit: Int, id: IDFilter, syncId: StringFilter, publicId: StringFilter, creationDate: StringFilter, modificationDate: StringFilter, rank: FloatFilter, createdBy: FiberyUserFilter, cc: EmailEmailContactCollectionFilter, cc1: StringFilter, date: StringFilter, deletedInEmail: StringFilter, deliveredTo: StringFilter, email: StringFilter, emailUrl: StringFilter, files: FiberyFileCollectionFilter, folder: StringFilter, from: EmailEmailContactFilter, from1: StringFilter, name: StringFilter, originalMessageId: StringFilter, replies: EmailEmailCollectionFilter, replyToText: StringFilter, thread: EmailEmailFilter, thread1: StringFilter, to: EmailEmailContactCollectionFilter, to1: StringFilter, rubric: IntFilter): [EmailEmail]
  emailsFrom(orderBy: EmailEmailOrder, limit: Int, id: IDFilter, syncId: StringFilter, publicId: StringFilter, creationDate: StringFilter, modificationDate: StringFilter, rank: FloatFilter, createdBy: FiberyUserFilter, cc: EmailEmailContactCollectionFilter, cc1: StringFilter, date: StringFilter, deletedInEmail: StringFilter, deliveredTo: StringFilter, email: StringFilter, emailUrl: StringFilter, files: FiberyFileCollectionFilter, folder: StringFilter, from: EmailEmailContactFilter, from1: StringFilter, name: StringFilter, originalMessageId: StringFilter, replies: EmailEmailCollectionFilter, replyToText: StringFilter, thread: EmailEmailFilter, thread1: StringFilter, to: EmailEmailContactCollectionFilter, to1: StringFilter, rubric: IntFilter): [EmailEmail]
  emailsTo(orderBy: EmailEmailOrder, limit: Int, id: IDFilter, syncId: StringFilter, publicId: StringFilter, creationDate: StringFilter, modificationDate: StringFilter, rank: FloatFilter, createdBy: FiberyUserFilter, cc: EmailEmailContactCollectionFilter, cc1: StringFilter, date: StringFilter, deletedInEmail: StringFilter, deliveredTo: StringFilter, email: StringFilter, emailUrl: StringFilter, files: FiberyFileCollectionFilter, folder: StringFilter, from: EmailEmailContactFilter, from1: StringFilter, name: StringFilter, originalMessageId: StringFilter, replies: EmailEmailCollectionFilter, replyToText: StringFilter, thread: EmailEmailFilter, thread1: StringFilter, to: EmailEmailContactCollectionFilter, to1: StringFilter, rubric: IntFilter): [EmailEmail]
  name: String
}

input EmailEmailContactInput {
  rank: Float
}

input EmailEmailContactOrder {
  id: Order
  syncId: Order
  publicId: Order
  creationDate: Order
  modificationDate: Order
  rank: Order
  createdBy: FiberyUserOrder
  deletedInEmail: Order
  email: Order
  name: Order
}

type EmailEmailContactBackgroundJob {
  jobId: String
  actions: EmailEmailContactOperations
}

type EmailEmailContactOperations {
  executeAsBackgroundJob: EmailEmailContactBackgroundJob
  create(rank: Float): MutationResult
  createBatch(data: [EmailEmailContactInput]): MutationResult
  update(rank: Float): MutationResult
  updateBatch(data: [EmailEmailContactInput]): MutationResult
  delete: MutationResult
  script(script: String): MutationResult
  scriptBatch(data: [ScriptInput]): MutationResult
  sendWebRequest(httpRequestConfig: String): MutationResult
  sendWebRequestBatch(data: [SendWebRequestInput]): MutationResult
  updateEmailsCc(filter: EmailEmailFilter, fields: EmailEmailInput): MutationResult
  updateEmailsCcBatch(data: [UpdateEmailsCcInput]): MutationResult
  updateEmailsFrom(filter: EmailEmailFilter, fields: EmailEmailInput): MutationResult
  updateEmailsFromBatch(data: [UpdateEmailsFromInput]): MutationResult
  updateEmailsTo(filter: EmailEmailFilter, fields: EmailEmailInput): MutationResult
  updateEmailsToBatch(data: [UpdateEmailsToInput]): MutationResult
  notifyCreatedBy(subject: String, message: String, notifyAuthor: Boolean): MutationResult
  notifyCreatedByBatch(data: [NotifyCreatedByInput]): MutationResult
  notifyUsers(to: [FiberyUserFilter], subject: String, message: String, notifyAuthor: Boolean, noEmptySend: Boolean): MutationResult
  notifyUsersBatch(data: [NotifyUsersInput]): MutationResult
  revokeAccessViaCreatedBy: MutationResult
  countOfEntities: Int
  listEntities: [Entity]
}

input EmailEmailContactFilter {
  orderBy: EmailEmailContactOrder
  limit: Int
  offset: Int
  id: IDFilter
  syncId: StringFilter
  publicId: StringFilter
  creationDate: StringFilter
  modificationDate: StringFilter
  rank: FloatFilter
  createdBy: FiberyUserFilter
  deletedInEmail: StringFilter
  email: StringFilter
  emailsCc: EmailEmailCollectionFilter
  emailsFrom: EmailEmailCollectionFilter
  emailsTo: EmailEmailCollectionFilter
  name: StringFilter
}

input EmailEmailContactCollectionFilter {
  isEmpty: Boolean
  contains: [EmailEmailContactFilter]
  containsAny: [EmailEmailContactFilter]
  notContains: [EmailEmailContactFilter]
  notContainsAny: [EmailEmailContactFilter]
}

type FiberyUser {
  active: Boolean
  id: ID
  role: String
  publicId: String
  creationDate: String
  modificationDate: String
  rank: Float
  email: String
  name: String
}

input FiberyUserInput {
  role: String
  rank: Float
  name: String
}

input FiberyUserOrder {
  active: Order
  id: Order
  role: Order
  publicId: Order
  creationDate: Order
  modificationDate: Order
  rank: Order
  email: Order
  name: Order
}

input FiberyUserFilter {
  orderBy: FiberyUserOrder
  limit: Int
  offset: Int
  active: BooleanFilter
  id: IDFilter
  role: StringFilter
  publicId: StringFilter
  creationDate: StringFilter
  modificationDate: StringFilter
  rank: FloatFilter
  email: StringFilter
  name: StringFilter
}

input FiberyUserCollectionFilter {
  isEmpty: Boolean
  contains: [FiberyUserFilter]
  containsAny: [FiberyUserFilter]
  notContains: [FiberyUserFilter]
  notContainsAny: [FiberyUserFilter]
}

type FiberyFile {
  contentLength: Float
  contentType: String
  id: ID
  name: String
  secret: String
  creationDate: String
  rank: Float
  urlExpiresAt: String
  url: String
}

input FiberyFileInput {
  name: String
  rank: Float
}

input FiberyFileOrder {
  contentLength: Order
  contentType: Order
  id: Order
  name: Order
  secret: Order
  creationDate: Order
  rank: Order
}

input FiberyFileFilter {
  orderBy: FiberyFileOrder
  limit: Int
  offset: Int
  contentLength: FloatFilter
  contentType: StringFilter
  id: IDFilter
  name: StringFilter
  secret: StringFilter
  creationDate: StringFilter
  rank: FloatFilter
}

input FiberyFileCollectionFilter {
  isEmpty: Boolean
  contains: [FiberyFileFilter]
  containsAny: [FiberyFileFilter]
  notContains: [FiberyFileFilter]
  notContainsAny: [FiberyFileFilter]
}

input StringFilter {
  is: String
  isNot: String
  contains: String
  notContains: String
  greater: String
  greaterOrEquals: String
  less: String
  lessOrEquals: String
  in: [String]
  notIn: [String]
  isNull: Boolean
}

input FloatFilter {
  is: Float
  isNot: Float
  greater: Float
  greaterOrEquals: Float
  less: Float
  lessOrEquals: Float
  in: [Float]
  notIn: [Float]
  isNull: Boolean
}

input IDFilter {
  is: ID
  isNot: ID
  in: [ID]
  notIn: [ID]
  isNull: Boolean
}

input IntFilter {
  is: Int
  isNot: Int
  greater: Int
  greaterOrEquals: Int
  less: Int
  lessOrEquals: Int
  in: [Int]
  notIn: [Int]
  isNull: Boolean
}

input BooleanFilter {
  is: Boolean
  isNull: Boolean
}

input DateRangeFilter {
  start: StringFilter
  end: StringFilter
  isNull: Boolean
}

type DateRange {
  start: String
  end: String
}

input DateRangeInput {
  start: String
  end: String
}

type AddressParts {
  poi: String
  postcode: String
  locality: String
  place: String
  district: String
  neighborhood: String
  address: String
  region: String
  country: String
}

input AddressPartsInput {
  poi: String
  postcode: String
  locality: String
  place: String
  district: String
  neighborhood: String
  address: String
  region: String
  country: String
}

type Location {
  latitude: Float
  longitude: Float
  fullAddress: String
  addressParts: AddressParts
}

input LocationFilter {
  isNull: Boolean
}

input LocationInput {
  latitude: Float
  longitude: Float
  fullAddress: String
  addressParts: AddressPartsInput
}

type RichField {
  secret: String
  md: String
  html: String
  jsonString: String
  text: String
}

type Document {
  id: ID
  secret: String
  name: String
  md: String
  html: String
  jsonString: String
  text: String
}

enum Order {
  ASC
  DESC
}

input DateRangeOrder {
  start: Order
  end: Order
}

type Entity {
  id: ID
  type: String
}

type Doc {
  secret: String
}

type MutationResult {
  message: String
  entities: [Entity]
  documents: [Doc]
}

enum JobStatus {
  EXECUTING
  FAILED
  COMPLETED
}

type ActionResult {
  actionName: String
  result: MutationResult
}

type BackgroundJob {
  status: JobStatus
  message: String
  database: String
  actions: [ActionResult]
}

input ScriptInput {
  script: String
}

input SendWebRequestInput {
  httpRequestConfig: String
}

input UpdateCcInput {
  filter: EmailEmailContactFilter
  fields: EmailEmailContactInput
}

input AppendContentToMessageInput {
  value: String
}

input PrependContentToMessageInput {
  value: String
}

input OverwriteMessageInput {
  value: String
}

input UpdateRepliesInput {
  filter: EmailEmailFilter
  fields: EmailEmailInput
}

input UpdateToInput {
  filter: EmailEmailContactFilter
  fields: EmailEmailContactInput
}

input AddFileToFilesFromUrlInput {
  name: String
  url: String
}

input AttachPdfToFilesUsingTemplateInput {
  name: String
  value: String
  htmlPage: Boolean
}

input NotifyCreatedByInput {
  subject: String
  message: String
  notifyAuthor: Boolean
}

input NotifyUsersInput {
  to: [FiberyUserFilter]
  subject: String
  message: String
  notifyAuthor: Boolean
  noEmptySend: Boolean
}

input UpdateEmailsCcInput {
  filter: EmailEmailFilter
  fields: EmailEmailInput
}

input UpdateEmailsFromInput {
  filter: EmailEmailFilter
  fields: EmailEmailInput
}

input UpdateEmailsToInput {
  filter: EmailEmailFilter
  fields: EmailEmailInput
}

type Mutation {
  emails(orderBy: EmailEmailOrder, limit: Int, offset: Int, id: IDFilter, syncId: StringFilter, publicId: StringFilter, creationDate: StringFilter, modificationDate: StringFilter, rank: FloatFilter, createdBy: FiberyUserFilter, cc: EmailEmailContactCollectionFilter, cc1: StringFilter, date: StringFilter, deletedInEmail: StringFilter, deliveredTo: StringFilter, email: StringFilter, emailUrl: StringFilter, files: FiberyFileCollectionFilter, folder: StringFilter, from: EmailEmailContactFilter, from1: StringFilter, name: StringFilter, originalMessageId: StringFilter, replies: EmailEmailCollectionFilter, replyToText: StringFilter, thread: EmailEmailFilter, thread1: StringFilter, to: EmailEmailContactCollectionFilter, to1: StringFilter, rubric: IntFilter): EmailEmailOperations
  emailContacts(orderBy: EmailEmailContactOrder, limit: Int, offset: Int, id: IDFilter, syncId: StringFilter, publicId: StringFilter, creationDate: StringFilter, modificationDate: StringFilter, rank: FloatFilter, createdBy: FiberyUserFilter, deletedInEmail: StringFilter, email: StringFilter, emailsCc: EmailEmailCollectionFilter, emailsFrom: EmailEmailCollectionFilter, emailsTo: EmailEmailCollectionFilter, name: StringFilter): EmailEmailContactOperations
}