# Generated by ariadne-codegen
# Source: src/agentic/ai/tools/fibery/graphql_client/queries.graphql

from typing import Optional

from .base_model import BaseModel


class UpdateEmailRubric(BaseModel):
    emails: Optional["UpdateEmailRubricEmails"]


class UpdateEmailRubricEmails(BaseModel):
    update: Optional["UpdateEmailRubricEmailsUpdate"]


class UpdateEmailRubricEmailsUpdate(BaseModel):
    message: Optional[str]


UpdateEmailRubric.model_rebuild()
UpdateEmailRubricEmails.model_rebuild()
